name: Release to PyPI

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python3 -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}